 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_afifo_autord.vhd
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_pkg.vhd
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_skid_buf.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_lite_if.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_reset.vhd
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_mm2s_cntrl_strm.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_mm2s_cmdsts_if.vhd  
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_s2mm_cmdsts_if.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_sofeof_gen.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_smple_sm.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_s2mm_sts_strm.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_s2mm_sts_mngr.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_s2mm_sm.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_s2mm_sg_if.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_s2mm_mngr.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_s2mm.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_rst_module.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_register_s2mm.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_register.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_reg_module.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_mm2s_sts_mngr.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_mm2s_sm.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_mm2s_sg_if.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_mm2s_mngr.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma_cmd_split.vhd 
 ../src/axi_dma_v6_00_a/hdl/vhdl/axi_dma.vhd 
